// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFrD6aeznXklVLaWsRmsYdgdqvwR8Gh0',
    appId: '1:85423021886:web:9785d5bcb9b503e97d566f',
    messagingSenderId: '85423021886',
    projectId: 'manga-reader-app-d48e3',
    authDomain: 'manga-reader-app-d48e3.firebaseapp.com',
    storageBucket: 'manga-reader-app-d48e3.firebasestorage.app',
    measurementId: 'G-EHGSPZDK5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs3QnyqcENHnQxBd7PJt1D_F1OHgKJG3g',
    appId: '1:85423021886:android:0b628e9638bc48607d566f',
    messagingSenderId: '85423021886',
    projectId: 'manga-reader-app-d48e3',
    storageBucket: 'manga-reader-app-d48e3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo6ER49GJ7ny_1jrXouLlFrN75UZNoAhc',
    appId: '1:85423021886:ios:849215e7048301007d566f',
    messagingSenderId: '85423021886',
    projectId: 'manga-reader-app-d48e3',
    storageBucket: 'manga-reader-app-d48e3.firebasestorage.app',
    iosBundleId: 'com.yourcompany.mangaReaderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo6ER49GJ7ny_1jrXouLlFrN75UZNoAhc',
    appId: '1:85423021886:ios:849215e7048301007d566f',
    messagingSenderId: '85423021886',
    projectId: 'manga-reader-app-d48e3',
    storageBucket: 'manga-reader-app-d48e3.firebasestorage.app',
    iosBundleId: 'com.yourcompany.mangaReaderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqFrD6aeznXklVLaWsRmsYdgdqvwR8Gh0',
    appId: '1:85423021886:web:65cca7c7c47e995f7d566f',
    messagingSenderId: '85423021886',
    projectId: 'manga-reader-app-d48e3',
    authDomain: 'manga-reader-app-d48e3.firebaseapp.com',
    storageBucket: 'manga-reader-app-d48e3.firebasestorage.app',
    measurementId: 'G-T0DB90FNR1',
  );
}
